trigger:
  - live

variables:
  DOCKER_CACHE_FOLDER: $(Pipeline.Workspace)/.docker-cache

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Cache@2
        inputs:
          key: 'es | "$(Agent.OS)" | ./Dockerfile'
          restoreKeys: |
             es | "$(Agent.OS)" | ./Dockerfile'
          path: $(DOCKER_CACHE_FOLDER)
          cacheHitVar: ES_CACHE_RESTORED
        displayName: Cache docker

      - task: CmdLine@2
        displayName: restore ES
        condition: eq(variables['ES_CACHE_RESTORED'], true)
        inputs:
          script: |
            docker save -o $(DOCKER_CACHE_FOLDER)/custom-es.tar custom-es:7.8.0

      - task: Docker@2
        displayName: Build ES
        inputs:
          command: build
          repository: custom-es
          tags: 7.8.0
          Dockerfile: ./Dockerfile

      - task: CmdLine@2
        displayName: backup ES
        inputs:
          script: |
            mkdir -p $(DOCKER_CACHE_FOLDER) &&
            docker save custom-es:7.8.0 > $(DOCKER_CACHE_FOLDER)/custom-es.tar

      - task: CmdLine@2
        displayName: Pull ES
        inputs:
          script: |
            docker pull cowsoul94/elasticsearch-with-analyzers:7.8.0

      - task: CmdLine@2
        displayName: run ES
        inputs:
          script: |
            docker run --rm -it -d -p 9200:9200 -e "discovery.type=single-node" custom-es:7.8.0

      - task: CmdLine@2
        displayName: echo
        inputs:
          script: |
            echo hello

      - task: CmdLine@2
        displayName: echo
        inputs:
          script: |
            curl http://localhost:9200/
