trigger:
  - live

jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        displayName: Build ES
        inputs:
          command: build
          tags: custom-es:7.8.0
          Dockerfile: ./Dockerfile

      - task: CmdLine@2
        displayName: Pull ES
        inputs: |
          docker pull cowsoul94/elasticsearch-with-analyzers:7.8.0
